### PR TITLE
Added rocketchat, tsuru, django-react-boilerplate

### PR DESCRIPTION
**Pull request by leogregianin**
## Contributing

(the same measurement rule as [awesome-made-by-russians ](https://github.com/gaearon/awesome-made-by-russians))

It's hard to calculate project popularity so we use stars as a measurement. It's not quite fair, but it is what we have here on Github.

If you want to add project to this list, please, make sure that:

- [x] The project was created by the developers born in Brazil
- [x] The project can't be just an personal, experimental or sample project
- [x] The project has more that **100 stars** on Github
- [x] One repository per PR/contribution - _avoid conflict and simplify review_

If they do, feel free to make a PR! 😁

### CODE REVIEW

**Comment by felipefialho** [comment]
@leogregianin can you sync with master?

**Comment by leogregianin** [comment]
@felipefialho synced

**Comment by felipefialho** [comment]
We have a lot of good projects made by brazilians 😁, amazing!

**Comment by leogregianin** [comment]
> We have a lot of good projects made by brazilians 😁, amazing!

There are many awesome projects made by Brazilians with more than 1k starts 😄

**Comment by felipefialho** [comment]
Yes, I don't know a lot of them, maybe later we can change the actual rule 😊

**Pull request merged**
