### PR TITLE
feat: add validations-br from reactivando

### PR DESCRIPTION
**Pull request by AZagatti**
## [validations-br](https://github.com/reactivando/validations-br)

- [X] The project was created by the developers born in Brazil
- [X] The project can't be just a personal, experimental or sample project
- [ ] The project has more than **100 stars** on Github _so close_
- [X] Place them in alphabetical order
- [X] One repository per PR/contribution - _avoid conflicts and simplify review_

### CODE REVIEW

**Comment by guibranco** [comment]
The project has only 68 stars. At least 100 stars is requested to be in the list.

**Comment by felipefialho** [comment]
Hi @AZagatti, nice project 😊

But for now we need to more then 100 stars... 😢

**Comment by AZagatti** [comment]
Sorry guys, I'll open another PR soon 😅

**Comment by felipefialho** [comment]
@AZagatti Almost there UHEAHUAE 😁

**Pull request closed without merging**
